# Generated by Django 4.0.3 on 2022-05-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=10)),
                ('lastName', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('gitHub', models.URLField()),
                ('userName', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
